import { IData } from "../types/types"

export const testDataLength6: IData = {
  length: 6,
  themes: [[1, "Спорт"], [2, 'Кино'], [3, 'Литература'], [4, 'Наука'], [5, 'Музыка'], [6, 'Искусство']],
  slides: {
    1: [['1943', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['1944', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['1945', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['1953', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]], 
    2: [['1985', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['1986', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['1987', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['1982', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]],
    3: [['2001', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['2002', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['2004', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['1999', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]], 
    4: [['2005', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['2006', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['2007', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['2008', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]], 
    5: [['2009', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['2010', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['2011', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['2016', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]],
    6: [['2017', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['2018', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['2019', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['2023', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]] 
  }
}

export const testDataLength5: IData = {
  length: 5,
  themes: [[1, "Спорт"], [2, 'Кино'], [3, 'Литература'], [4, 'Наука'], [5, 'Музыка']],
  slides: {
    1: [['1943', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['1944', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['1945', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['1953', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]], 
    2: [['1985', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['1986', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['1987', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['1982', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]],
    3: [['2001', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['2002', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['2004', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['1999', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]], 
    4: [['2005', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['2006', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['2007', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['2008', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]], 
    5: [['2009', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['2010', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['2011', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['2016', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]], 
  }
}

export const testDataLength2: IData = {
  length: 2,
  themes: [[1, "Спорт"], [2, 'Кино']],
  slides: {
    1: [['1943', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['1944', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['1945', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['1953', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]], 
    2: [['1985', '13 сентября — частное солнечное затмение, видимое в Южной Африке и части Антарктиды'], ['1986', 'Телескоп «Хаббл» обнаружил самую удалённую из всех обнаруженных галактик, получившую обозначение GN-z11'], ['1987', 'Компания Tesla официально представила первый в мире электрический грузовик Tesla Semi'], ['1982', "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."]],
  }
}